{
  flake.modules.homeManager.llm = { inputs, pkgs, lib, ... }: {
    home.packages = with inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system}; [
      claude-code
      cc-switch-cli
      hermes-one
      hermes-agent
      dsh
    ];

    # ────────────────────────────────────────────────────────────────────────
    # Hermes One (fathah/hermes-desktop) 不扫 PATH,只识别官方安装器布局:
    #   ~/.hermes/hermes-agent/venv/bin/python   (解释器)
    #   ~/.hermes/hermes-agent/hermes            (CLI 入口,作为 argv[1] 传入)
    # 它的一切调用都是  python <hermes> <args>  /  python -c <内联脚本>。
    # 而本机 hermes 由 nix 提供(hermes-agent 包),二进制在 profile 里,布局对不上,
    # 所以 app 判定「未安装」。这里在每次 switch 时重建一个桥接 shim:伪装成 venv
    # 解释器,把调用转发给 nix 版 hermes。
    # 依据 upstream: src/main/installer.ts (HERMES_HOME / HERMES_PYTHON /
    # HERMES_SCRIPT / checkInstallStatus / validateHermesHome)。
    # ────────────────────────────────────────────────────────────────────────
    home.activation.hermesBridge = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ -n "''${DRY_RUN:-}" ]; then
        exit 0
      fi

      # hermes 二进制:优先稳定 profile 软链(自动跟随 nix 更新),兜底 command -v。
      HERMES_BIN=""
      for p in "/etc/profiles/per-user/$(id -un)/bin/hermes" "$HOME/.nix-profile/bin/hermes"; do
        if [ -x "$p" ]; then HERMES_BIN="$p"; break; fi
      done
      if [ -z "$HERMES_BIN" ] && command -v hermes >/dev/null 2>&1; then
        HERMES_BIN="$(command -v hermes)"
      fi

      mkdir -p "$HOME/.hermes/hermes-agent/venv/bin"
      cat > "$HOME/.hermes/hermes-agent/venv/bin/python" <<'SHIM_EOF'
#!/usr/bin/env bash
# ============================================================================
# Hermes One bridge shim — generated by home-manager (llm.nix), do not edit.
#
# Hermes One (fathah/hermes-desktop) never scans PATH; it only recognizes the
# official-installer layout ~/.hermes/hermes-agent/{venv/bin/python,hermes}
# and drives hermes via:
#     python <hermes> <args...>        (gateway / dashboard / CLI chat)
#     python -c <script> <arg>         (voice STT/TTS inline helpers)
# This shim impersonates the venv interpreter and forwards both to the
# nix-built hermes (llm-agents.nix / nixpkgs hermes-agent).
# ============================================================================
set -u

# Resolve the real hermes binary (stable profile symlinks follow nix updates).
HERMES=""
for p in "/etc/profiles/per-user/$(id -un)/bin/hermes" "$HOME/.nix-profile/bin/hermes"; do
  if [ -x "$p" ]; then HERMES="$p"; break; fi
done
if [ -z "$HERMES" ] && command -v hermes >/dev/null 2>&1; then
  HERMES="$(command -v hermes)"
fi
if [ -z "$HERMES" ]; then
  echo "hermes bridge shim: hermes binary not found" >&2
  exit 127
fi

if [ "''${1:-}" = "-c" ]; then
  # Inline python helpers (voice STT/TTS): run them with hermes' python env so
  # hermes' site-packages (tools.*, agent.*, ...) is importable.
  HERMES_PY=$(grep -m1 '^export HERMES_PYTHON=' "$HERMES" 2>/dev/null | sed "s/^export HERMES_PYTHON='\\(.*\\)'/\\1/")
  SRC_ROOT=$(grep -m1 '^export HERMES_PYTHON_SRC_ROOT=' "$HERMES" 2>/dev/null | sed "s/^export HERMES_PYTHON_SRC_ROOT='\\(.*\\)'/\\1/")
  if [ -n "$HERMES_PY" ] && [ -n "$SRC_ROOT" ]; then
    export PYTHONPATH="$SRC_ROOT''${PYTHONPATH:+:$PYTHONPATH}"
    export HERMES_PYTHON_SRC_ROOT="$SRC_ROOT"
    export HERMES_HOME="''${HERMES_HOME:-$HOME/.hermes}"
    exec "$HERMES_PY" "$@"
  fi
  echo "hermes bridge shim: could not resolve HERMES_PYTHON from $HERMES" >&2
  exit 127
fi

# CLI path: drop the HERMES_SCRIPT placeholder (argv[1]), forward the rest.
[ $# -gt 0 ] && shift
exec "$HERMES" "$@"
SHIM_EOF
      chmod +x "$HOME/.hermes/hermes-agent/venv/bin/python"

      if [ -z "$HERMES_BIN" ]; then
        echo "hermesBridge: hermes binary not found, leaving hermes symlink untouched" >&2
      else
        ln -sfn "$HERMES_BIN" "$HOME/.hermes/hermes-agent/hermes"
      fi
    '';
  };
}
